
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build_image:
  image: docker:git

  services:
  - docker:dind

  script:
    - echo "31.15.25.100 hub.rnd.alterway.fr" >/etc/hosts
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master
    - adapt_to_new_machinery
