version: "3"
services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    beedrill:
        image: beedrill:latest
        depends_on:
            - redis


networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1400

