version: "3"

services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    beedrill:
        image: beedrill
        command:
            - "worker"
        depends_on:
            - redis
        deploy:
          replicas: 3


networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1400
    external:
      name: lulz_default
