version: "3"
services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    beedrill-scratch:
        image: beedrill-scratch:latest
        depends_on:
            - redis
