version: "3"

services:
    one-mega-nginx:
        image: one-mega-nginx:latest
    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    beedrill:
        image: beedrill:latest
        depends_on:
            - redis

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1400
