version: "3"

services:
#    one-mega-nginx:
#      image: one-mega-nginx:latest
    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    beedrill:
        image: beedrill:latest
        command:
          - "/usr/local/bin/beedrill"
          - "worker"
        depends_on:
            - redis
        deploy:
          replicas: 1


networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1400
    external:
      name: lulz_default

