version: "3"

services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf

    beedrill:
        image: hub.rnd.alterway.fr/wolphin-project/beedrill:master
        command:
            - "worker"
        depends_on:
            - redis
        deploy:
          replicas: 3


networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1400
    external:
      name: lulz_default
