version: "3"

services:
    redis:
        image: redis:3.2.9
        ports:
            - "6379:6379"

    worker:
        image: wolphinproject/benchdrill:latest
        command:
          - "worker"
        depends_on:
            - redis
        deploy:
          replicas: 5

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1400
    external:
      name: benchdrill_default

